//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatcher
    {
        public int dispatcher_id { get; set; }
        public string hub_location { get; set; }
    
        public virtual User_Info User_Info { get; set; }
    }
}
