//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Complaints = new HashSet<Complaint>();
            this.Trackings = new HashSet<Tracking>();
        }
    
        public int order_id { get; set; }
        public string receiver_mobile { get; set; }
        public string receiver_address { get; set; }
        public int package_count { get; set; }
        public float amount { get; set; }
        public string status { get; set; }
        public int customer_id { get; set; }
        public int personnel_id { get; set; }
        public string receiver_name { get; set; }
        public string receiver_email { get; set; }
        public string package_type { get; set; }
    
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual Delivery_Personnel Delivery_Personnel { get; set; }
        public virtual User_Info User_Info { get; set; }
        public virtual ICollection<Tracking> Trackings { get; set; }
    }
}
