//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int tracking_id { get; set; }
        public string departed_from { get; set; }
        public string reached_at { get; set; }
        public string destination { get; set; }
        public string status { get; set; }
        public System.DateTime updated_at { get; set; }
        public int order_id { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
