//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public User_Info()
        {
            this.Complaints = new HashSet<Complaint>();
            this.Orders = new HashSet<Order>();
        }
    
        public int user_Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public int role_id { get; set; }
        public string status { get; set; }
        public string token { get; set; }
    
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual Delivery_Personnel Delivery_Personnel { get; set; }
        public virtual Dispatcher Dispatcher { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Role Role { get; set; }
    }
}
